#!/bin/bash
# Generated by vim-plug
# Tue 27 Jan 2015 03:05:36 PM AEDT

vim +PlugUpdate +qa

PLUG_HOME=/home/laurent/.vim/plugged

cd $PLUG_HOME/csapprox/ && git reset --hard 7981dac
cd $PLUG_HOME/ctrlp.vim/ && git reset --hard b5d3fe6
cd $PLUG_HOME/html5.vim/ && git reset --hard a47aa2d
cd $PLUG_HOME/nerdcommenter/ && git reset --hard 6549cfd
cd $PLUG_HOME/nerdtree/ && git reset --hard 3b98a7f
cd $PLUG_HOME/pyflakes-vim/ && git reset --hard 92ab1d3
cd $PLUG_HOME/snipmate.vim/ && git reset --hard f5a75d0
cd $PLUG_HOME/supertab/ && git reset --hard 454c06e
cd $PLUG_HOME/syntastic/ && git reset --hard cb64516
cd $PLUG_HOME/taglist.vim/ && git reset --hard 53041fb
cd $PLUG_HOME/vim-airline/ && git reset --hard 13ee9f4
cd $PLUG_HOME/vim-colors-solarized/ && git reset --hard 528a59f
cd $PLUG_HOME/vim-fugitive/ && git reset --hard 933f6a1
cd $PLUG_HOME/vim-hilinks/ && git reset --hard e2ae9d4
cd $PLUG_HOME/vim-howdoi/ && git reset --hard 479a607

